### ISSUE TITLE
upload_asset with Upload URL error

### ISSUE THREAD

**Issue by hannesa2** [whiteinge/ok.sh#64] opened 2018-10-17 11:39 UTC
I can create a release but when I try to upload a asset to release run 

`./scripts/ok.sh -v upload_asset $USER $REPO 13452549 javadoc.jar application/x-tar < ./build/libs/javadoc.jar`

in run into 

> parse error: Invalid numeric literal at line 1, column 9
> jq parse error; invalid JSON.
> ok.sh INFO: Remaining next link follows: 50
> ./scripts/ok.sh: line 1652: upload_url: Upload URL could not be retrieved.

I use `jq` version jq-1.5

Any ideas ?

**Comment by whiteinge** [comment] 2018-10-17 14:44
This is #46. The HTTP headers are getting output along with the JSON and causing the parse error. I've been neglecting debugging it because I think this needs to be split into two separate functions (0066212). Sorry for the trouble; I'll take another look.

**Comment by whiteinge** [comment] 2018-10-18 00:37
This may be a different error than I thought. I couldn't reproduce it, but I found a few other problems with that function that may be contributing. Could you please give the script in #65 a shot? ([Direct link to script here.](https://github.com/whiteinge/ok.sh/blob/9f6b1ec681049bd5a6d163e6d62212bcbc458b61/ok.sh))

If you see an error again will you please run it with `-vvv` and paste the output here?
**Redact the two(!) `Authorization: Basic` lines.**
```
./scripts/ok.sh -vvv upload_asset $USER $REPO 13452549 javadoc.jar application/x-tar < ./build/libs/javadoc.jar 2>&1
```

**Comment by whiteinge** [comment] 2018-10-20 01:50
Thanks for that. Unfortunately this one has me stumped. I must have a bug somewhere where the headers and body aren't getting separated properly because the response you pasted seems to be valid JSON and the requisite `upload_url` field is present. I just haven't been able to reproduce it. 😕

GitHub makes uploading assets pretty cumbersome since we need to fetch, parse, & derive info from multiple API calls. I'm not confident that I can make this workflow reliable so I may just pull this function out and replace it with docs.

All the steps are below. Hopefully they'll work better for you while I continue to noodle on a better solution.

```sh
# Create release:
USER="whiteinge"
REPO="testrepo"
TAG="0.1.2"
FILE_NAME="foo.zip"
FILE_PATH="./tests/foo.zip"

# Create new release and upload:
ok.sh create_release "$USER" "$REPO" "$TAG" _filter='.upload_url' \
    | sed 's/{.*$/?name='"$FILE_NAME"'/' \
    | xargs -I@ ok.sh _post @ filename="$FILE_PATH"

# Or find existing release and upload:
ok.sh list_releases "$USER" "$REPO" \
    | awk -v "tag=$TAG" -F'\t' '$2 == tag { print $3 }' \
    | xargs -I@ ok.sh release "$USER" "$REPO" @ _filter='.upload_url' \
    | sed 's/{.*$/?name='"$FILE_NAME"'/' \
    | xargs -I@ ok.sh _post @ filename="$FILE_PATH"
```

**Comment by hannesa2** [comment] 2018-10-31 14:58
`./internalDevelopment/scripts/ok.sh list_releases "$USER" "$REPO"`

> parse error: Invalid numeric literal at line 1, column 9
> jq parse error; invalid JSON.
> curl: (23) Failed writing body (1205 != 1370)

any ideas ?

**Comment by hannesa2** [comment] 2018-10-31 15:01
I see as a huge advantage, when command pipe json out to extra. Then it's much easier to debug and see on which step it fails

**Comment by whiteinge** [comment] 2018-10-31 17:47
That's unexpected that `list_releases` would fail when used alone and other GET queries would not. But I'm glad we're narrowing the problem down!

Will you please run that again with the `-j` flag to avoid invoking jq? I'm interested to see the top few lines. What I'm expecting is that we'll see a few HTTP response headers output above the JSON response body.

If that's the case, few Qs:
- What OS and curl version are you running?
- What shell is `/usr/bin/env sh` on your machine?
- Are you hitting vanilla https://api.github.com or something else like GH enterprise?

If my above guess is correct then I'd be interested to see the following output for where the response headers transition into the response body. (Note, I think the `-A` flag here is a GNU-ism.)

```
curl -nsSig "https://api.github.com/repos/${USER}/${REPO}/releases | cat -A"
```

**Comment by hannesa2** [comment] 2018-11-01 13:29
- It's happen on Linux and macOS
- shell 
```
$ ps -p $$
  PID TTY           TIME CMD
75208 ttys005    0:00.01 sh
```

- I'm using a private repos (is this the question ?)

and `./internalDevelopment/scripts/ok.sh list_releases "$USER" "$REPO" > output.txt` delivers

[output.txt](https://github.com/whiteinge/ok.sh/files/2538662/output.txt)

**Comment by whiteinge** [comment] 2018-11-02 19:14
When I send that output through the `list_releases` pipeline it outputs all the releases via jq as expected, so I'm not sure yet how to reproduce this ☹️. My guess is something is preventing [this match](https://github.com/whiteinge/ok.sh/blob/365282d/ok.sh#L761) and jq is getting passed headers instead of just the body.

Two more requests, please.

* Does [this version](https://github.com/whiteinge/ok.sh/blob/42d61800c6949db73cca77179862780a08c501aa/ok.sh) have the same problem?
* Please run `ok.sh -x list_releases "$USER" "$REPO" 2> ok.sh.log` and upload that file as well.

**Comment by dubiouscript** [comment] 2018-11-22 15:59
> curl: (23) Failed writing body (1205 != 1370)
:/
chk permissions ?

**Comment by whiteinge** [comment] 2019-11-14 19:29
Closing since we switched to matching on CRLF. Feel free to reopen if the problem persists.

**Closed by whiteinge** 2019-11-14 19:29 UTC
Labels: bug
